"""Generates a markdown QA report from test results, optionally sends to Slack."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

import httpx

from aiqa.models import TestResult

if TYPE_CHECKING:
    from aiqa.config import ClientConfig


STATUS_ICON = {
    "pass": "✅",
    "fail": "❌",
    "skip": "⏭️",
    "error": "💥",
}


def generate_report(
    client_config: "ClientConfig",
    results: list[TestResult],
    run_started: datetime,
    run_finished: datetime,
    output_dir: Path,
) -> Path:
    """Write a markdown report and return the path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    date_str = run_started.strftime("%Y-%m-%d")
    time_str = run_started.strftime("%H%M%S")
    report_path = output_dir / f"{client_config.name}-{date_str}-{time_str}.md"

    passed = sum(1 for r in results if r.status == "pass")
    failed = sum(1 for r in results if r.status == "fail")
    errors = sum(1 for r in results if r.status == "error")
    skipped = sum(1 for r in results if r.status == "skip")
    total = len(results)
    duration = (run_finished - run_started).total_seconds()

    lines: list[str] = []

    # Header
    lines += [
        f"# AiQA Report — {client_config.name}",
        f"**Store:** {client_config.base_url}  ",
        f"**Date:** {run_started.strftime('%Y-%m-%d %H:%M:%S')}  ",
        f"**Duration:** {duration:.1f}s  ",
        f"**Agent:** AiQA v0.1.0 (browser-use + Claude)",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Result | Count |",
        f"|--------|-------|",
        f"| ✅ Pass | {passed} |",
        f"| ❌ Fail | {failed} |",
        f"| 💥 Error | {errors} |",
        f"| ⏭️ Skipped | {skipped} |",
        f"| **Total** | **{total}** |",
        "",
    ]

    overall = "✅ ALL PASSED" if failed == 0 and errors == 0 else f"❌ {failed + errors} ISSUE(S) FOUND"
    lines += [f"**Overall: {overall}**", "", "---", ""]

    # Test case results table
    lines += ["## Test Results", ""]
    lines += ["| Test Case | Name | Status | Checks | Duration |"]
    lines += ["|-----------|------|--------|--------|----------|"]
    for r in results:
        icon = STATUS_ICON.get(r.status, "?")
        checks_str = f"{r.passed_checks}/{r.total_checks}" if r.total_checks > 0 else "—"
        lines.append(
            f"| {r.test_id} | {r.name} | {icon} {r.status.upper()} | {checks_str} | {r.duration_seconds}s |"
        )
    lines += ["", "---", ""]

    # Detailed results per test case
    lines += ["## Detailed Results", ""]

    for r in results:
        icon = STATUS_ICON.get(r.status, "?")
        lines += [
            f"### {r.test_id}: {r.name}",
            f"**Status:** {icon} {r.status.upper()}  ",
            f"**Duration:** {r.duration_seconds}s  ",
        ]

        if r.notes:
            lines += [f"**Notes:** {r.notes}  ", ""]

        if r.error:
            lines += [f"**Error:** `{r.error}`  ", ""]

        if r.checks:
            lines += [
                "#### Verification Checks",
                "",
                "| Check | Expected | Actual | Result |",
                "|-------|----------|--------|--------|",
            ]
            for c in r.checks:
                icon_c = "✅" if c.passed else "❌"
                lines.append(f"| {c.name} | {c.expected} | {c.actual} | {icon_c} |")
            lines.append("")

        if r.screenshots:
            lines += ["#### Screenshots", ""]
            for ss in r.screenshots:
                label = Path(ss).name
                lines.append(f"- `{ss}` — {label}")
            lines.append("")

        if r.raw_data:
            lines += [
                "<details>",
                "<summary>Raw API Data (click to expand)</summary>",
                "",
                "```json",
                json.dumps(r.raw_data, indent=2),
                "```",
                "",
                "</details>",
                "",
            ]

        lines += ["---", ""]

    # Footer
    lines += [
        f"*Report generated by AiQA v0.1.0*  ",
        f"*{run_finished.strftime('%Y-%m-%d %H:%M:%S')}*",
    ]

    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


async def send_slack_notification(
    webhook_url: str,
    client_name: str,
    results: list[TestResult],
    report_path: Path,
) -> None:
    """Send a summary to Slack if a webhook URL is configured."""
    if not webhook_url:
        return

    passed = sum(1 for r in results if r.status == "pass")
    failed = sum(1 for r in results if r.status == "fail")
    errors = sum(1 for r in results if r.status == "error")
    total = len(results)

    overall_icon = "✅" if failed == 0 and errors == 0 else "❌"
    status_lines = "\n".join(
        f"{STATUS_ICON.get(r.status, '?')} {r.test_id}: {r.name}"
        for r in results
    )

    message = {
        "text": (
            f"{overall_icon} *AiQA Report — {client_name}*\n"
            f"Passed: {passed}/{total} | Failed: {failed} | Errors: {errors}\n\n"
            f"{status_lines}\n\n"
            f"Report saved: `{report_path}`"
        )
    }

    async with httpx.AsyncClient() as client:
        try:
            await client.post(webhook_url, json=message, timeout=10.0)
        except Exception as e:
            print(f"Warning: Slack notification failed — {e}")
